;/*FB_PKG_DELIM*/

__d("PolarisCancelDialogItem.react",["fbt","IGDSDialogItem.react","react"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=(i||(i=d("react"))).c,k=i;function a(a){var b=j(3);a=a.onClose;var c;b[0]===Symbol["for"]("react.memo_cache_sentinel")?(c=h._("__JHASH__ko1T7DvDF-J__JHASH__"),b[0]=c):c=b[0];b[1]!==a?(c=k.jsx(d("IGDSDialogItem.react").IGDSDialogItem,{onClick:a,children:c}),b[1]=a,b[2]=c):c=b[2];return c}g["default"]=a}),226);
__d("PolarisEmbedDialogItem_user.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"PolarisEmbedDialogItem_user",selections:[{kind:"RequiredField",field:{alias:null,args:null,kind:"ScalarField",name:"pk",storageKey:null},action:"THROW",path:"pk"},{alias:null,args:null,kind:"ScalarField",name:"username",storageKey:null}],type:"XDTUserDict",abstractKey:null};e.exports=a}),null);
__d("PolarisEmbedDialogItem.react",["fbt","CometRelay","IGDSDialogItem.react","JSResourceForInteraction","PolarisEmbedDialogItem_user.graphql","react","useIGDSLazyDialog"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j,k=(j||(j=d("react"))).c,l=j,m=c("JSResourceForInteraction")("PolarisEmbedModal.react").__setRef("PolarisEmbedDialogItem.react");function a(a){var e=k(8),f=a.onClose;a=a.user;var g=d("CometRelay").useFragment(i!==void 0?i:i=b("PolarisEmbedDialogItem_user.graphql"),a);a=c("useIGDSLazyDialog")(m);var j=a[0];e[0]!==j||e[1]!==g.pk||e[2]!==g.username||e[3]!==f?(a=function(){var a;j({analyticsContext:"profilePage",ownerId:g.pk,productType:"profile",username:(a=g.username)!=null?a:""},f)},e[0]=j,e[1]=g.pk,e[2]=g.username,e[3]=f,e[4]=a):a=e[4];a=a;var n;e[5]===Symbol["for"]("react.memo_cache_sentinel")?(n=h._("__JHASH__7DRnhAyDomb__JHASH__"),e[5]=n):n=e[5];e[6]!==a?(n=l.jsx(d("IGDSDialogItem.react").IGDSDialogItem,{onClick:a,children:n}),e[6]=a,e[7]=n):n=e[7];return n}g["default"]=a}),226);
__d("usePolarisIsUserEmbeddable_user.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"usePolarisIsUserEmbeddable_user",selections:[{alias:null,args:null,kind:"ScalarField",name:"is_embeds_disabled",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"is_private",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"is_unpublished",storageKey:null}],type:"XDTUserDict",abstractKey:null};e.exports=a}),null);
__d("usePolarisIsUserEmbeddable",["CometRelay","usePolarisIsUserEmbeddable_user.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){a=d("CometRelay").useFragment(h!==void 0?h:h=b("usePolarisIsUserEmbeddable_user.graphql"),a);return a.is_embeds_disabled!==!0&&a.is_private!==!0&&a.is_unpublished!==!0}g["default"]=a}),98);
__d("usePolarisRestrictMutation_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="7456259841095672"}),null);
__d("usePolarisRestrictMutation.graphql",["usePolarisRestrictMutation_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"target_user_ids"}],c=[{kind:"Variable",name:"target_user_ids",variableName:"target_user_ids"}],d={alias:null,args:null,kind:"ScalarField",name:"pk",storageKey:null},e={alias:null,args:null,concreteType:"XDTRelationshipInfoDict",kind:"LinkedField",name:"friendship_status",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"is_restricted",storageKey:null}],storageKey:null};return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"usePolarisRestrictMutation",selections:[{alias:null,args:c,concreteType:"XDTUserDict",kind:"LinkedField",name:"xdt_api__v1__restrict_action__restrict_many",plural:!0,selections:[d,e],storageKey:null}],type:"Mutation",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"usePolarisRestrictMutation",selections:[{alias:null,args:c,concreteType:"XDTUserDict",kind:"LinkedField",name:"xdt_api__v1__restrict_action__restrict_many",plural:!0,selections:[d,e,{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null}],storageKey:null}]},params:{id:b("usePolarisRestrictMutation_instagramRelayOperation"),metadata:{is_distillery:!0},name:"usePolarisRestrictMutation",operationKind:"mutation",text:null}}}();e.exports=a}),null);
__d("usePolarisRestrictMutation",["fbt","CometRelay","react","useIGDSToaster","usePolarisRestrictMutation.graphql"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j;e=j||d("react");e.useCallback;var k=e.c;function a(){var a=k(6),e=c("useIGDSToaster")(),f=d("CometRelay").useMutation(i!==void 0?i:i=b("usePolarisRestrictMutation.graphql")),g=f[0];f=f[1];var j;a[0]!==g||a[1]!==e?(j=function(a){a=a.target_user_ids;g({onCompleted:function(){e.add({message:h._("__JHASH__AM7D7j8uuEB__JHASH__"),target:"bottom"})},variables:{target_user_ids:a}})},a[0]=g,a[1]=e,a[2]=j):j=a[2];j=j;var l;a[3]!==j||a[4]!==f?(l=[j,f],a[3]=j,a[4]=f,a[5]=l):l=a[5];return l}g["default"]=a}),226);